add RegistryPolicy resource
aws-cloudformation/aws-cloudformation-resource-providers-ecr pull request #19
Opened 2021-01-11 17:46 UTC by bradgr

*Description of changes:*

* The RegistryPolicy schema definition.
* CRUD operations for Uluru support (not supporting List)
* Unit Tests for the CRUD operations.

*Example CloudFormation templates*
JSON:
~~~
{
    "Resources": {
       "TestRegistryPolicy": {
              "Type": "AWS::ECR::RegistryPolicy",
              "Properties": {
                "PolicyText": {
                        "Version":"2012-10-17",
                        "Statement":[
                            {
                                "Sid":"ReplicationAccessCrossAccount",
                                "Effect":"Allow",
                                "Principal":{
                                    "AWS":"arn:aws:iam::123456789:root"
                                },
                                "Action":[
                                    "ecr:CreateRepository",
                                    "ecr:ReplicateImage"
                                ],
                                "Resource": "arn:aws:ecr:us-west-2:123412341234:repository/*"
                            }
                        ]
                    }
              }
        }
    }    
}
~~~

YAML:
~~~
Resources:
  TestRegistryPolicy:
    Type: 'AWS::ECR::RegistryPolicy'
    Properties:
      PolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: UpdatedRegistryPolicy
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::123456789:root'
            Action:
              - 'ecr:CreateRepository'
              - 'ecr:ReplicateImage'
            Resource: 'arn:aws:ecr:us-west-2:123412341234:repository/*'
~~~

*Testing*
* mvn package
* cfn test
* cfn submit
* manual testing
  * created CFN stack with example template above and verified RegistryPolicy was applied to my registry.
  * deleted stack after creation and verified registry policy deleted from registry
  * created stack then updated with new template, verifying changes seen in ECR registry policy

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-12 23:24 UTC, apurvmahajan approved these changes

2021-01-13 21:27 UTC, michaelb990 requested changes
Generally looks good. Curious about one thing.

2021-01-13 21:38 UTC, bradgr commented on aws-ecr-registrypolicy/src/main/java/software/amazon/ecr/registrypolicy/UpdateHandler.java
> +        // Read first to verify resource exists
It currently fails as CFN makes an update call (as opposed to create call) on a resource that doesn't exist.

2021-01-14 18:54 UTC, michaelb990 approved these changes
LGTM!

2021-01-14 18:58 UTC, merged